spring.application.name=SDPBackend
server.port=1234
#server.port=${PORT:8080}
#server.port=${PORT:8080}
#server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:53833/railway
spring.datasource.username=root
spring.datasource.password=NCnQDfIPZaaQHpfjLXTjHvocskGnxfnK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sreevatsalsreevatsal@gmail.com
spring.mail.password=vhgv clho lcjf kcwo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2